# ./04n-plaform-navi-credentials.yaml
- name: Displaying Platform Navigator Credentials
  hosts: "localhost"
  gather_facts: false
  tasks:
    - include_vars: vars_deployment.yaml

    - name: Retrieving Platform Navigator URL
      ansible.builtin.shell:
        cmd: oc get platformnavigator cp4i-navigator -n tools -o jsonpath='{range .status.endpoints[?(@.name=="navigator")]}{.uri}{end}'
      register: createsecret

    - debug:
        var: "CP4I Platform UI URL:"

    - debug:
        var: createsecret.stdout

