apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-eventprocessing-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-eventprocessing-1.1.8
  publisher: IBM
  image: icr.io/cpopen/ibm-eventprocessing-operator-catalog@sha256:d31ed04609cc3a3c4456f1a116a2a33f621905f9c74511e4fa2255a408c8986b
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 30m0s
