apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-eventautomation-flink-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-eventautomation-flink-1.1.8
  publisher: IBM
  image: icr.io/cpopen/ibm-eventautomation-flink-operator-catalog@sha256:fc0de95c8ac91f63e9559443bb2439690890ddad5fe7c33ff8f8c2af57020bc3
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 30m0s
