apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: aspera-hsts-operator
  namespace: openshift-operators
spec:
  channel: v1.5
  name: aspera-hsts-operator 
  source: aspera-operators
  sourceNamespace: openshift-marketplace