apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-eventendpointmanagement
  namespace: openshift-operators
spec:
  channel: v11.2
  name: ibm-eventendpointmanagement 
  source: ibm-eventendpointmanagement-catalog
  sourceNamespace: openshift-marketplace