apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: ea-flink-demo
  namespace: tools
spec:
  flinkConfiguration:
    license.use: EventAutomationNonProduction
    license.license: L-HRZF-DWHH7A
    license.accept: 'true'
    execution.checkpointing.interval: '5000'
    state.backend.type: rocksdb
    state.checkpoints.num-retained: '3'
    taskmanager.numberOfTaskSlots: '4'
    table.exec.source.idle-timeout: 30 s
    json.ignore-parse-errors: 'true'
    restart-strategy.type: 'none'
    env.java.opts.jobmanager: '-Djavax.net.ssl.trustStore=/certs/eventautomation.jks -Djavax.net.ssl.trustStorePassword=eventautomationstore'
    env.java.opts.taskmanager: '-Djavax.net.ssl.trustStore=/certs/eventautomation.jks -Djavax.net.ssl.trustStorePassword=eventautomationstore'
  serviceAccount: flink
  podTemplate:
    apiVersion: v1
    kind: Pod
    metadata:
      name: pod-template
    spec:
      containers:
        - name: flink-main-container
          volumeMounts:
            - name: flink-logs
              mountPath: /opt/flink/log
            - name: truststore
              mountPath: /certs
      volumes:
        - name: flink-logs
          emptyDir: {}
        - name: truststore
          secret:
            items:
              - key: eventautomation.jks
                path: eventautomation.jks
            secretName: eventautomation-truststore
  jobManager:
    replicas: 1
    resource:
      memory: 2048m
      cpu: 1
  taskManager:
    resource:
      memory: 3072m
      cpu: 4
  mode: native