---
# ./02a-certmanager.yaml
- name: Managing Cert Manager Instance
  hosts: "localhost"
  gather_facts: false
  tasks:
    - include_vars: vars_deployment.yaml

############################################
#  REMOVAL
############################################

# install mysql database service
    - name: Remove openshift cert-manager-operator subscription
      kubernetes.core.k8s:
        src: artifacts/cert-manager/3-cm-subscription.yaml
        state: absent
      when:  action  == 'remove'

    - name: Remove a cert manager operatorGroup
      kubernetes.core.k8s:
        src: artifacts/cert-manager/2-cm-operatorgroup.yaml
        state: absent
      when:  action  == 'remove'

    - name: Remove a cert-manager namespace
      kubernetes.core.k8s:
        src: artifacts/cert-manager/1-cm-namespace.yaml
        state: absent
      when:  action  == 'remove'

############################################
# CREATION
############################################
    - name: Create cert-manager namespace
      k8s:
        src: artifacts/cert-manager/1-cm-namespace.yaml
        state: present
      when:  action  == 'install'

    - name: Create a cert manager operatorGroup
      k8s:
        src: artifacts/cert-manager/2-cm-operatorgroup.yaml
        state: present
      when: action  == 'install'

    - name: Create openshift cert-manager-operator subscription
      k8s:
        src: artifacts/cert-manager/3-cm-subscription.yaml
        state: present
      when:  action  == 'install'


 



