# ./04n-plaform-navi-credentials.yaml
- name: Displaying License ibm-common-services Credentials
  hosts: "localhost"
  gather_facts: false
  tasks:
    - include_vars: vars_deployment.yaml

    - name: Retrieving License Service URL
      ansible.builtin.shell:
        cmd: oc get route ibm-licensing-service-instance -n ibm-common-services -o jsonpath={.spec.host}
      register: createsecret

    - name: Retrieving License Service API Token
      ansible.builtin.shell:
        cmd: oc get secret ibm-licensing-token -o jsonpath={.data.token} -n ibm-common-services | base64 -D
      register: createsecret2

    - name: Print License Service Messages
      ansible.builtin.debug:
        msg:
        - "License Service URL: https://{{createsecret.stdout}}"
        - "License Service API Token: {{createsecret2.stdout}}"

    # - name: Retrieving License Service Password
    #   ansible.builtin.shell:
    #     cmd: oc get secret integration-admin-initial-temporary-credentials -n ibm-common-services -o jsonpath='{.data.password}' | base64 --decode
    #   register: createsecret3

    # - debug:
    #     msg: "License Service Password:  {{createsecret3.stdout}}"
