# ./04n-plaform-navi-credentials.yaml
- name: Displaying Platform Navigator Credentials
  hosts: "localhost"
  gather_facts: false
  tasks:
    - include_vars: vars_deployment.yaml

    - name: Retrieving Platform Navigator URL
      ansible.builtin.shell:
        cmd: oc get platformnavigator cp4i-navigator -n {{mynamespace}} -o jsonpath='{range .status.endpoints[?(@.name=="navigator")]}{.uri}{end}'
      register: createsecret

    - name: Retrieving Platform Navigator Username
      ansible.builtin.shell:
        cmd: oc get secret integration-admin-initial-temporary-credentials -n ibm-common-services -o jsonpath='{.data.username}' | base64 --decode
      register: createsecret2

    - name: Retrieving Platform Navigator Password
      ansible.builtin.shell:
        cmd: oc get secret integration-admin-initial-temporary-credentials -n ibm-common-services -o jsonpath='{.data.password}' | base64 --decode
      register: createsecret3

    - name: Prints Platform Navigator Information
      ansible.builtin.debug:
        msg:
        - "CP4I Platform UI URL: {{createsecret.stdout}}"
        - "CP4I Platform UI Username: {{createsecret2.stdout}}"
        - "CP4I Platform UI Password:  {{createsecret3.stdout}}"

