apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-eventstreams 
  namespace: openshift-operators
spec:
  channel: v3.3
  name: ibm-eventstreams 
  source: ibm-eventstreams 
  sourceNamespace: openshift-marketplace