apiVersion: operator.ibm.com/v1alpha1
kind: IBMLicensing
metadata:
  name: instance
  namespace: ibm-common-services
  labels:
    app.kubernetes.io/instance: ibm-licensing-operator
    app.kubernetes.io/managed-by: ibm-licensing-operator
    app.kubernetes.io/name: ibm-licensing
spec:
  version: 1.20.9
  apiSecretToken: ibm-licensing-token
  datasource: datacollector
  httpsEnable: true
  chargebackEnabled: true
  features:
    hyperThreading:
      threadsPerCore: 2